server:
  port: 9090
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      
      
zuul:
  routes:
    eureka-client1:
      path: /getName/**
      serviceId: eureka-client1
      strip-prefix: false
      
